apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: egress-meter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: egress-meter
subjects:
  - kind: ServiceAccount
    name: egress-meter
    namespace: system
