apiVersion: v1
kind: Service
metadata:
  name: egress-meter
  namespace: system
spec:
  selector:
    app.bex.co/component: egress-meter
  ports:
    - name: metrics
      port: 9091
      targetPort: metrics
