apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-plugins
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:bex-co/bex.git
    targetRevision: main
    path: deploy/gitops/charts/traefik-plugins
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
