/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by dashboard/scripts/generate-email-brand.mjs from dashboard/src/style.css. DO NOT EDIT.

package email

// The dashboard palette (dashboard/src/style.css :root, light theme — which
// itself mirrors eden-cms-v2) converted to email-safe values: email clients
// support neither CSS custom properties nor oklch(), so each token is baked
// to sRGB hex. Regenerate with `yarn generate:email-brand` from dashboard/;
// the dashboard test suite fails when this file drifts from style.css.
const (
	BrandBackground        = "#f8f8fa" // --background: oklch(0.98 0.002 260)
	BrandCard              = "#ffffff" // --card: oklch(1 0 0)
	BrandForeground        = "#090b0f" // --foreground: oklch(0.15 0.008 260)
	BrandMuted             = "#e9ebef" // --muted: oklch(0.94 0.005 260)
	BrandMutedForeground   = "#575e69" // --muted-foreground: oklch(0.48 0.02 260)
	BrandPrimary           = "#307d03" // --primary: oklch(0.52 0.16 138.3)
	BrandPrimaryForeground = "#f8f8f8" // --primary-foreground: oklch(0.98 0 0)
	BrandBorder            = "#d4d8dd" // --border: oklch(0.88 0.008 260)
	BrandDestructive       = "#db0003" // --destructive: oklch(0.55 0.24 27)
)

const (
	// BrandFontFamily is the dashboard's font stack — already an email-safe
	// set (system-ui with universal fallbacks).
	BrandFontFamily = "system-ui, Avenir, Helvetica, Arial, sans-serif"
	// BrandRadiusPx is --radius (0.65rem) at the root 16px em size.
	BrandRadiusPx = 10
)
