apiVersion: v1
kind: Service
metadata:
  name: ssh-gateway
  namespace: system
spec:
  selector:
    app.kubernetes.io/name: bex-ssh-gateway
  ports:
    - name: ssh
      port: 2222
      targetPort: ssh
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
