#!/usr/bin/env bash
# Render the Homebrew formula for a bex CLI release to stdout.
#   VERSION=0.1.0 bash scripts/bex-cli-formula.sh <checksums.txt>
# checksums.txt is the release artifact produced by cli-release.yml
# (`sha256sum bex-<version>-<os>-<arch>.tar.gz` lines).
set -euo pipefail

checksums="${1:?usage: VERSION=X.Y.Z bex-cli-formula.sh <checksums.txt>}"
: "${VERSION:?set VERSION to the release version (X.Y.Z)}"

# VERSION is interpolated into Ruby source and URLs; reject anything that is
# not a plain (optionally pre-release-suffixed) semver before rendering.
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.-]+)?$ ]] ||
  { echo "error: VERSION '$VERSION' is not a plain semver" >&2; exit 1; }

sha_for() {
  local target="bex-${VERSION}-$1.tar.gz" sha
  # Exact $2 match on sha256sum's text-mode output — the one dialect
  # cli-release.yml produces; first match wins so a duplicated line cannot
  # render a corrupt multi-hash formula.
  sha="$(awk -v f="$target" '$2 == f { print $1; exit }' "$checksums")"
  [ -n "$sha" ] || { echo "error: no checksum for $target in $checksums" >&2; exit 1; }
  printf '%s' "$sha"
}

# The release tag contains a slash; GitHub encodes it as %2F in asset URLs.
base="https://github.com/bex-co/bex/releases/download/bex-cli%2Fv${VERSION}"

# Resolve every platform before rendering: a failing $(…) inside the heredoc
# would not abort the script, and a partial formula must never be emitted.
sha_darwin_arm64="$(sha_for darwin-arm64)"
sha_darwin_amd64="$(sha_for darwin-amd64)"
sha_linux_arm64="$(sha_for linux-arm64)"
sha_linux_amd64="$(sha_for linux-amd64)"

cat <<EOF
# Generated by scripts/bex-cli-formula.sh for bex-cli/v${VERSION} — do not edit.
class Bex < Formula
  desc "Bex CLI: Render-compatible command line for the Bex platform"
  homepage "https://github.com/bex-co/bex"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base}/bex-${VERSION}-darwin-arm64.tar.gz"
      sha256 "${sha_darwin_arm64}"
    end
    on_intel do
      url "${base}/bex-${VERSION}-darwin-amd64.tar.gz"
      sha256 "${sha_darwin_amd64}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/bex-${VERSION}-linux-arm64.tar.gz"
      sha256 "${sha_linux_arm64}"
    end
    on_intel do
      url "${base}/bex-${VERSION}-linux-amd64.tar.gz"
      sha256 "${sha_linux_amd64}"
    end
  end

  def install
    # Homebrew strips a sole top-level archive directory during staging, so
    # the binary is usually at the root; fall back to the nested layout.
    bin.install(File.exist?("bex") ? "bex" : Dir["bex-*/bex"].fetch(0))
  end

  test do
    assert_match "bex v#{version}", shell_output("#{bin}/bex --version")
  end
end
EOF
