#!/usr/bin/env bash
# Push bex CI secrets from .env into THIS repo's GitHub Actions secrets.
#   1. cp .env.example .env     2. fill .env (gitignored)     3. bash scripts/gh-secrets.sh
# Requires the gh CLI, authed (`gh auth login`). Repo is inferred from the origin remote.
# Secrets go in via stdin/file — never as command-line args (which would leak in ps).
set -euo pipefail
cd "$(dirname "$0")/.."

[ -f .env ] || { echo "ERROR: .env not found — run: cp .env.example .env  (then fill it)"; exit 1; }
command -v gh >/dev/null || { echo "ERROR: gh CLI not found — brew install gh && gh auth login"; exit 1; }

set -a; . ./.env; set +a

set_secret_value() {
  local name="$1" environment="${2:-}"
  if [ -n "$environment" ]; then
    gh secret set "$name" --env "$environment"
  else
    gh secret set "$name"
  fi
}

secret_scope_note() {
  [ -z "$1" ] || printf ' (environment: %s)' "$1"
}

set_scalar() {
  local name="$1" environment="${2:-}" val="${!1:-}"
  [ "$#" -le 2 ] || { echo "ERROR: set_scalar accepts only NAME [ENVIRONMENT]" >&2; return 2; }
  [ -n "$val" ] || { echo "skip  $name (empty in .env)"; return; }
  printf '%s' "$val" | set_secret_value "$name" "$environment"
  echo "set   $name$(secret_scope_note "$environment")"
}
set_file() {
  local name="$1" path="$2" environment="${3:-}"
  [ "$#" -le 3 ] || { echo "ERROR: set_file accepts only NAME PATH [ENVIRONMENT]" >&2; return 2; }
  [ -f "$path" ] || { echo "ERROR: $name file not found: $path"; exit 1; }
  set_secret_value "$name" "$environment" < "$path"
  echo "set   $name  (from $path)$(secret_scope_note "$environment")"
}

# KRATOS_*/HYDRA_*/BEX_BOOTSTRAP_*/BEX_SMTP_* feed deploy.yml's auth steps (docs/ADR012-auth.md;
# KRATOS_COURIER_SMTP_URI + BEX_SMTP_USERNAME/PASSWORD are the shared SMTP relay, §11);
# BAO_* (OpenBao Shamir unseal keys + root token, generated by bao-init.sh)
# feed deploy.yml's OpenBao unseal step (docs/ADR013-secrets.md) so re-deploys unseal
# idempotently.
for s in HCLOUD_TOKEN TF_STATE_BUCKET TF_STATE_ENDPOINT TF_STATE_REGION TF_STATE_ACCESS_KEY TF_STATE_SECRET_KEY \
         KRATOS_SECRETS_DEFAULT KRATOS_SECRETS_COOKIE KRATOS_SECRETS_CIPHER \
         HYDRA_SECRETS_SYSTEM HYDRA_SECRETS_COOKIE HYDRA_OIDC_PAIRWISE_SALT \
         BEX_BOOTSTRAP_CLIENT_SECRET OPENFGA_PRESHARED_KEY \
         BEX_GITHUB_OIDC_CLIENT_ID BEX_GITHUB_OIDC_CLIENT_SECRET \
         KRATOS_COURIER_SMTP_URI BEX_SMTP_USERNAME BEX_SMTP_PASSWORD \
         AGE_BACKUP_PRIVATE_KEY AGE_BACKUP_PRIVATE_KEY_PREVIOUS \
         BAO_UNSEAL_KEY_1 BAO_UNSEAL_KEY_2 BAO_UNSEAL_KEY_3 BAO_ROOT_TOKEN \
         BEX_AGENT_SNAPSHOT_S3_ENDPOINT BEX_AGENT_SNAPSHOT_S3_BUCKET \
         BEX_AGENT_SNAPSHOT_S3_REGION BEX_AGENT_SNAPSHOT_S3_PREFIX \
         BEX_AGENT_SNAPSHOT_S3_ACCESS_KEY BEX_AGENT_SNAPSHOT_S3_SECRET_KEY \
         BEX_DISK_SNAPSHOT_ENDPOINT BEX_DISK_SNAPSHOT_BUCKET \
         BEX_DISK_SNAPSHOT_REGION BEX_DISK_SNAPSHOT_PREFIX \
         BEX_DISK_SNAPSHOT_ACCESS_KEY BEX_DISK_SNAPSHOT_SECRET_KEY \
         BEX_DISK_SNAPSHOT_READ_ACCESS_KEY BEX_DISK_SNAPSHOT_READ_SECRET_KEY \
         BEX_DISK_SNAPSHOT_AGE_PUBLIC_KEY; do
  set_scalar "$s"
done
# The externally issued wildcard material is available only to the protected
# production deploy. bex installs it at the edge but never calls a DNS provider.
set_file BEX_ONBEX_TLS_CERT "${BEX_ONBEX_TLS_CERT_FILE:?set BEX_ONBEX_TLS_CERT_FILE in .env}" production-deploy
set_file BEX_ONBEX_TLS_KEY "${BEX_ONBEX_TLS_KEY_FILE:?set BEX_ONBEX_TLS_KEY_FILE in .env}" production-deploy
set_file BEX_SSH_PUBLIC_KEY  "${BEX_SSH_PUBLIC_KEY_FILE:?set BEX_SSH_PUBLIC_KEY_FILE in .env}"
set_file BEX_SSH_PRIVATE_KEY "${BEX_SSH_PRIVATE_KEY_FILE:?set BEX_SSH_PRIVATE_KEY_FILE in .env}"
# The control-plane host-key pin (w1/m68 t006, docs/ADR019-infra-credentials.md):
# a multi-line known_hosts value; set_scalar pipes it verbatim. Re-capture and
# re-push after a control-plane template rotation (ADR053) — the deploy/app-
# cluster/openbao-drill workflows assert mandatory-pin mode and abort without it.
set_scalar BEX_SSH_KNOWN_HOSTS

# Optional: the bex-co/homebrew-tap write deploy key (cli-release.yml's
# formula-push step); skipping leaves the release workflow's tap step off.
if [ -n "${BEX_TAP_PUSH_KEY_FILE:-}" ]; then
  set_file BEX_TAP_PUSH_KEY "$BEX_TAP_PUSH_KEY_FILE"
else
  echo "skip  BEX_TAP_PUSH_KEY (no BEX_TAP_PUSH_KEY_FILE in .env)"
fi

echo "done. verify with: gh secret list"
