fragment EnvironmentFields on Environment {
  id
  projectId
  name
  ownerId
  createdAt
  serviceIds
  databaseIds
  keyValueIds
  envGroupIds
  protectedStatus
  networkIsolationEnabled
  ipAllowList
}

query Environments($projectId: String!) {
  environments(projectId: $projectId) {
    ...EnvironmentFields
  }
}

mutation CreateEnvironment($name: String!, $projectId: String!) {
  createEnvironment(name: $name, projectId: $projectId) {
    ...EnvironmentFields
  }
}

mutation RenameEnvironment($id: String!, $name: String!) {
  renameEnvironment(id: $id, name: $name) {
    ...EnvironmentFields
  }
}

mutation DeleteEnvironment($id: String!) {
  deleteEnvironment(id: $id)
}

mutation SetEnvironmentServices($id: String!, $serviceIds: [String!]!) {
  setEnvironmentServices(id: $id, serviceIds: $serviceIds) {
    ...EnvironmentFields
  }
}

mutation SetEnvironmentDatabases($id: String!, $databaseIds: [String!]!) {
  setEnvironmentDatabases(id: $id, databaseIds: $databaseIds) {
    ...EnvironmentFields
  }
}

mutation SetEnvironmentKeyValues($id: String!, $keyValueIds: [String!]!) {
  setEnvironmentKeyValues(id: $id, keyValueIds: $keyValueIds) {
    ...EnvironmentFields
  }
}

mutation SetEnvironmentEnvGroups($id: String!, $envGroupIds: [String!]!) {
  setEnvironmentEnvGroups(id: $id, envGroupIds: $envGroupIds) {
    ...EnvironmentFields
  }
}

mutation SetEnvironmentACL(
  $id: String!
  $protectedStatus: String!
  $networkIsolationEnabled: Boolean!
  $ipAllowList: [String!]
) {
  setEnvironmentACL(
    id: $id
    protectedStatus: $protectedStatus
    networkIsolationEnabled: $networkIsolationEnabled
    ipAllowList: $ipAllowList
  ) {
    ...EnvironmentFields
  }
}
