apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../default
  - api-pdb.yaml
  - pg-sni-proxy-lb.yaml
  - kv-sni-proxy-lb.yaml
  - edge-proxy-network-policy.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: bex-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: bex-api
                topologyKey: kubernetes.io/hostname
