apiVersion: v1
kind: Service
metadata:
  name: bex-kv-sni-proxy-public
  namespace: bex-system
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.bex.co/component: kv-sni-proxy
  ports:
    - name: valkey
      port: 6379
      targetPort: 6379
      nodePort: 31892
      protocol: TCP
