//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by bpf2go; DO NOT EDIT.

package egressmeter

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfLpmV4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type bpfLpmV6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type bpfResourceKey struct {
	_         structs.HostLayout
	AppId     [64]int8
	Namespace [64]int8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	BexCountPublicEgress *ebpf.ProgramSpec `ebpf:"bex_count_public_egress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Diagnostics    *ebpf.MapSpec `ebpf:"diagnostics"`
	ExcludedV4     *ebpf.MapSpec `ebpf:"excluded_v4"`
	ExcludedV6     *ebpf.MapSpec `ebpf:"excluded_v6"`
	PodV4Resources *ebpf.MapSpec `ebpf:"pod_v4_resources"`
	PodV6Resources *ebpf.MapSpec `ebpf:"pod_v6_resources"`
	ResourceBytes  *ebpf.MapSpec `ebpf:"resource_bytes"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Diagnostics    *ebpf.Map `ebpf:"diagnostics"`
	ExcludedV4     *ebpf.Map `ebpf:"excluded_v4"`
	ExcludedV6     *ebpf.Map `ebpf:"excluded_v6"`
	PodV4Resources *ebpf.Map `ebpf:"pod_v4_resources"`
	PodV6Resources *ebpf.Map `ebpf:"pod_v6_resources"`
	ResourceBytes  *ebpf.Map `ebpf:"resource_bytes"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Diagnostics,
		m.ExcludedV4,
		m.ExcludedV6,
		m.PodV4Resources,
		m.PodV6Resources,
		m.ResourceBytes,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	BexCountPublicEgress *ebpf.Program `ebpf:"bex_count_public_egress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.BexCountPublicEgress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
