import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    "cuckoo-network",
    "vision",
    {
      type: "category",
      label: "Cuckoo AI",
      items: ["Cuckoo AI/cuckoo-ai", "Cuckoo AI/ai-node"],
    },
    {
      type: "category",
      label: "Cuckoo Chain",
      items: ["Cuckoo Chain/cuckoo-chain", "Cuckoo Chain/full-node"],
    },
    "How does Cuckoo work",
    "token",
    "roadmap",
    "team",
  ],
};

export default sidebars;
