yarn translate i18n/es/code.json es
yarn translate i18n/fa/code.json fa
yarn translate i18n/fr/code.json fr
yarn translate i18n/hi/code.json hi
yarn translate i18n/id/code.json id
yarn translate i18n/ja/code.json ja
yarn translate i18n/ko/code.json ko
yarn translate i18n/pt/code.json pt
yarn translate i18n/ru/code.json ru
yarn translate i18n/th/code.json th
yarn translate i18n/tr/code.json tr
yarn translate i18n/vi/code.json vi
yarn translate i18n/zh/code.json zh
