apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: activator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: activator
subjects:
  - kind: ServiceAccount
    name: activator
    namespace: bex-system
