apiVersion: v1
kind: Service
metadata:
  name: kv-sni-proxy
  namespace: system
spec:
  selector:
    app.bex.co/component: kv-sni-proxy
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
    - name: metrics
      port: 9093
      targetPort: metrics
